# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_ID',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
