# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='testcase_input',
            field=models.FileField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='testcase_output',
            field=models.FileField(upload_to=None),
        ),
    ]
