# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_ID',
            field=models.EmailField(max_length=200),
        ),
    ]
