# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170103_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user_ID',
            field=models.EmailField(max_length=120),
        ),
    ]
