# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_submission_ques_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_submissions',
            field=models.CharField(default=b'0', max_length=10),
        ),
    ]
