# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_total_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='total_submissions',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
