# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170112_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='testcase_input',
            field=models.FileField(upload_to=b'Testcase'),
        ),
        migrations.AlterField(
            model_name='question',
            name='testcase_output',
            field=models.FileField(upload_to=b'Testcase'),
        ),
    ]
