# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170115_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleprofile',
            name='profile_url',
        ),
    ]
