# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_googleprofile_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
