# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_question_accuracy'),
        ('app', '0008_announcement'),
    ]

    operations = [
    ]
