# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20170117_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='total_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
