# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170118_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'images'),
        ),
    ]
